### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by zumma93**
initial commit

### CODE REVIEW

**Comment by zumma93** [comment]
confirmed

**Comment by nk-coding** [comment]
Hi @zumma93 , probably not the best way to reach out, but I just saw your fork / this PR.
First, thx for giving this a try, and sry for the limited documentation.
Just so you know, this repo (nk-coding/dokka-html-mdx-transform) is just by test repo (thus also outdated and barely working), the "real" version can be found at https://github.com/graphglue/dokka-html-mdx-transform (I also fixed the docs there a bit).
I also released a new version of @graphglue/dokka-docusaurus with support for Docusaurus 3.x.
In case you want to do sth with this doc transformer, and have any questions (or experience any issues), feel free to reach out to me

**Comment by zumma93** [comment]
Hi Krieger,
thank you for interest!

As you said I have met many problems since i tried to use this plugin. I do
not know there is a new version for docusaurus 3.x integration. In fact I
had to downgrade docusaurus into 2.4.x, and I had confusion to use action
core component so that i had to hard code the paths as like src, dest,
modules in index.js. And the more I found some index.html are to be
ignored. I mean the index.html at the level of modules was missed ... so I
tried to define modules as upper layer of directory and then error was
thrown because there was a empty directory that sends a null argument to
transform funtion.

Thanks to you, i will try again by reading the updated documents with
docusaurus 3.x ... let me be back after another try. Thank you so much!


2024년 5월 31일 (금) 오후 11:44, Niklas Krieger ***@***.***>님이 작성:

**Comment by nk-coding** [comment]
If you want an example, this stuff is currently used at https://github.com/graphglue/graph-glue/tree/main/website.
This results in this website:
https://graphglue.github.io/api/graphglue-core/io.github.graphglue/index- 
The workflow responsible for building the website can be found here: https://github.com/graphglue/graph-glue/blob/main/.github/workflows/deploy.yml

Regarding the issues you had: in particular, the missing index.html sounds strange, however without knowing what exactly you work with (is it a multi-module project, dokka version, kotlin version, build system, ...) it's difficult to debug for me.
I'm sure there's a way to adapt the action so that it works for you.
If you want, I may be able to help you with setting it up for your project, feel free to reach out to me via mail (niklask.coding@gmail.com) or Discord (nkcoding)

**Comment by zumma93** [comment]
WOW!

I will be back in 2 days. This is weekend in south korea ^^


2024년 6월 1일 (토) 오전 12:23, Niklas Krieger ***@***.***>님이 작성:

**Pull request closed without merging**
